name: Quick Tests

on:
  pull_request:
    branches: [ create_image ]
  workflow_dispatch:

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Quick syntax check
      run: |
        python -m py_compile runpod_handler.py
        echo "✅ Syntax check passed"
    
    - name: Dockerfile validation
      run: |
        if [ ! -f Dockerfile ]; then
          echo "❌ Dockerfile missing"
          exit 1
        fi
        echo "✅ Dockerfile exists"
    
    - name: Environment template check
      run: |
        if [ ! -f .env.example ]; then
          echo "❌ .env.example missing"
          exit 1
        fi
        echo "✅ Environment template exists"